### ISSUE TITLE
[SUGGESTION] Upload to CurseForge

### ISSUE THREAD

**Issue by Rebel459** [Aegrithas/ImprovedLodestones#1]
Hi there, love the mod. Would really like to be able to include it in my modpack, but am unfortunately unable to as I need to maintain a modpack across both Modrinth and CurseForge with full parity.
As such, it would be greatly appreciated if you could consider uploading this mod to CurseForge

Thanks for your time

**Comment by Aegrithas** [comment]
Thanks for your interest! I've uploaded it to CurseForge, and I will let you know when it gets approved.

**Comment by Aegrithas** [comment]
It just got approved; you can find it here: [https://www.curseforge.com/minecraft/mc-mods/improved-lodestones](https://www.curseforge.com/minecraft/mc-mods/improved-lodestones).

**Comment by Rebel459** [comment]
Thank you so much! That's a massive help, really glad I'm able to include it in my pack - I love the design choices you made with the lodestone and compass reworks
