### ISSUE TITLE
[Enhancement] Update to 1.20.5/1.20.6/1.21

### ISSUE THREAD

**Issue by Arch1bold** [Aegrithas/ImprovedLodestones#2]
Requires (probably) changing the NBT tags to the new component system
(lodestone_tracker and net.minecraft.component.type.LodestoneTrackerComponent)
and some of the network code (PacketHandler?)

**Comment by Aegrithas** [comment]
I've added support for `1.20.6`. `1.21` shouldn't take long. I have no intent to support `1.20.5` unless you have a specific reason for it.

**Comment by Aegrithas** [comment]
As expected, `1.21` was _almost_ identical to the `1.20.6` version, so it's out now too.
