### ISSUE TITLE
Lodestone Compass disappears when dropped when installed with Loot Beams

### ISSUE THREAD

**Issue by Cephelo** [Aegrithas/ImprovedLodestones#3]
Disclaimer: Sinytra Connector is involved.  That being said, the stacktraces do specifically mention both mods.

Mods installed:
[Improved Lodestones 1.0](https://www.curseforge.com/minecraft/mc-mods/improved-lodestones/files/5029703)
[Forgified Fabric API 0.92.2-1.11.8](https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api/files/5387432)
[Sinytra Connector (beta 45)](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector/files/5605667)
[Loot Beams 1.2.6](https://www.curseforge.com/minecraft/mc-mods/loot-beams/files/5548970)
Forge 47.3.0

Behavior: When dropping a lodestone compass, the item vanishes entirely.

Stacktrace:
[lootbeams-imp_lodes-stacktrace.txt](https://github.com/user-attachments/files/16596724/lootbeams-imp_lodes-stacktrace.txt)

No crashlog was generated.
Please let me know if you need anything else.
Sister issue: shiroroku/LootBeams#49

**Comment by Aegrithas** [comment]
Interesting... does it only happen if the compass has been bound to a lodestone, or does it happen to unbound compasses as well?

To be honest I didn't know Sinytra Connector existed, so I'm going to need to look into it, and it might take a while. Depending on how Sintrya Connector works, it might not be a problem I can fix (short of porting to Forge, which I don't want to do; other people are welcome to, though). All this to say, there may not be a quick fix, and there may not be any fix at all.

**Comment by Cephelo** [comment]
It only happens to compasses bound to a lodestone, unbound compasses are not affected.

**Comment by Aegrithas** [comment]
Interesting... does it happen for other items with NBT data? For instance, a shulker box with something it it or a banner that has had some patterns applied?

**Comment by Cephelo** [comment]
Just lodestone compasses, from my testing.  Maybe it's related to the colored tooltip?  Not sure.

**Comment by Aegrithas** [comment]
Cool, thanks for doing a bit of testing for me.

**Comment by Aegrithas** [comment]
Okay, I think I've identified the issue, and it's entirely fixable! It doesn't appear to have anything to do with Sinytra. I'll try to get a fix out quickly, but my development environment might fight me going back to 1.20.1 from 1.21, so it might not be as quick as I'd like. Entirely by coincidence, I actually already fixed the bug in 1.20.6 and 1.21, so if you can upgrade, that should provide an immediate fix for you.

**Comment by Aegrithas** [comment]
Alright, [v1.0.1](https://github.com/Aegrithas/ImprovedLodestones/releases/tag/v1.0.1%2B1.20.1) should fix it. If you don't mind, could you test it from that release before I publish versions to Modrinth and Curseforge, just to make sure it does actually resolve the issue?

**Comment by Cephelo** [comment]
Lodestone compasses are now dropped normally, it works!  Thank you so much :)
